/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import forme.potvrde.PotvrdaOBrisanju;
import domen.Clan;
import domen.Clanarina;
import domen.Radnik;

import java.util.ArrayList;

import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import modeli.ModelTabeleClanova;   
import javax.swing.JFrame;

import operacije.Operacija;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author STEFAN94
 */
public class ClanoviForma extends javax.swing.JFrame {

    private Clan izmenjenClan;
    private Clan noviClan;
    private GlavnaForma glavnaForma;
    private Clanarina evidentiranaClanarina;
    private Radnik ulogovaniRadnik;
    private ArrayList<Clan> listaClanova;

    public ClanoviForma(GlavnaForma glavnaForma) {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.glavnaForma = glavnaForma;
        ulogovaniRadnik = glavnaForma.getUlogovaniRadnik();
        this.getContentPane().setBackground(java.awt.Color.lightGray);
        initComponents();
        listaClanova = new ArrayList<>();
        popuniTabeluClanova();
        int brojFormi = glavnaForma.getBrFormiClan();
        glavnaForma.setBrFormiClan(++brojFormi);
        glavnaForma.getBtnPretragaClanova().setEnabled(false);
        btnEvidentirajClanarinu.setEnabled(false);
        btnIzmeniPodatkeOClanu.setEnabled(false);
        btnObrisiClana.setEnabled(false);
        btnZaduzenja.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPretragaClanova = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClanovi = new javax.swing.JTable();
        btnDodajNovogClana = new javax.swing.JButton();
        btnIzmeniPodatkeOClanu = new javax.swing.JButton();
        btnObrisiClana = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();
        btnEvidentirajClanarinu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnZaduzenja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clanovi");
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        txtPretragaClanova.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPretragaClanovaKeyReleased(evt);
            }
        });

        tblClanovi.setBackground(new java.awt.Color(0, 102, 102));
        tblClanovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClanovi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClanoviMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClanovi);

        btnDodajNovogClana.setText("Dodaj novog clana");
        btnDodajNovogClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajNovogClanaActionPerformed(evt);
            }
        });

        btnIzmeniPodatkeOClanu.setText("Izmeni podatke o clanu");
        btnIzmeniPodatkeOClanu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniPodatkeOClanuActionPerformed(evt);
            }
        });

        btnObrisiClana.setText("Obrisi clana");
        btnObrisiClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiClanaActionPerformed(evt);
            }
        });

        btnNazad.setText("Nazad");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        btnEvidentirajClanarinu.setText("Evidentiraj clanarinu");
        btnEvidentirajClanarinu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvidentirajClanarinuActionPerformed(evt);
            }
        });

        jLabel1.setText("Pretraga clanova(Ime/Prezime/JMBG):");

        btnZaduzenja.setText("Zaduzenja");
        btnZaduzenja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaduzenjaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDodajNovogClana)
                                .addGap(18, 18, 18)
                                .addComponent(btnIzmeniPodatkeOClanu)
                                .addGap(18, 18, 18)
                                .addComponent(btnObrisiClana)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(btnZaduzenja)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEvidentirajClanarinu))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPretragaClanova, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNazad)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPretragaClanova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNazad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajNovogClana)
                    .addComponent(btnIzmeniPodatkeOClanu)
                    .addComponent(btnObrisiClana)
                    .addComponent(btnEvidentirajClanarinu)
                    .addComponent(btnZaduzenja))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPretragaClanovaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretragaClanovaKeyReleased

        String pretraga = txtPretragaClanova.getText().trim();
        Clan clan = new Clan();
        clan.setIme(pretraga);
        clan.setPrezime(pretraga);
        long jmbg =0;
        try {
            jmbg = Long.parseLong(pretraga);
        } catch (Exception e) {
            jmbg = 0;
        }
        clan.setJmbg(jmbg);
        KlijentskiZahtev klijentskiZahtev = new KlijentskiZahtev();
        klijentskiZahtev.setOperacija(Operacija.PRETRAZI_CLANOVE);
        klijentskiZahtev.setParametar(clan);

        Komunikacija.getInstanca().posaljiKlijentskiZahtev(klijentskiZahtev);
        ServerskiOdgovor serverskiOdgovor = Komunikacija.getInstanca().primiServerskiOdgovor();

        ArrayList<Clan> listaClanova = (ArrayList<Clan>) serverskiOdgovor.getOdgovor();

        ModelTabeleClanova modelTabeleClanova = (ModelTabeleClanova) tblClanovi.getModel();
        modelTabeleClanova.azurirajTabelu(listaClanova);

        btnEvidentirajClanarinu.setEnabled(false);
        btnIzmeniPodatkeOClanu.setEnabled(false);
        btnObrisiClana.setEnabled(false);
        btnZaduzenja.setEnabled(false);
//        System.out.println("Izvrsilo se!");

//        String pretraga = txtPretragaClanova.getText().toLowerCase();
//        String patternZaPretragu = "^" + pretraga + ".*";
//        ArrayList<Clan> listaPretrazenihClanova = new ArrayList<>();
//        for (Clan clan : listaClanova) {
//            
//            String jmbgString = clan.getJmbg() + "";
//
//            if (clan.getIme().toLowerCase().matches(patternZaPretragu)
//                    || clan.getPrezime().toLowerCase().matches(patternZaPretragu)
//                    || clan.getIme().concat(" ").concat(clan.getPrezime()).toLowerCase().matches(patternZaPretragu)
//                    || clan.getPrezime().concat(" ").concat(clan.getIme()).toLowerCase().matches(patternZaPretragu)
//                    || jmbgString.matches(patternZaPretragu)) {
//                listaPretrazenihClanova.add(clan);
//            }
//        }
//        ModelTabeleClanova mtc = (ModelTabeleClanova) tblClanovi.getModel();
//        mtc.azurirajTabelu(listaPretrazenihClanova);
        System.out.println("Izvrsilo se!");

    }//GEN-LAST:event_txtPretragaClanovaKeyReleased

    private void btnIzmeniPodatkeOClanuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniPodatkeOClanuActionPerformed

        IzmeniPodatkeOClanuForma ipocf = new IzmeniPodatkeOClanuForma(this, true);
        ipocf.pack();
        ipocf.setVisible(true);

    }//GEN-LAST:event_btnIzmeniPodatkeOClanuActionPerformed

    public int vratiIndeksSelektovanogClana() {

        int selektovaniClan = tblClanovi.getSelectedRow();
        return selektovaniClan;

    }

    private void btnObrisiClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiClanaActionPerformed

        int clanZaBrisanje = vratiIndeksSelektovanogClana();
        if (clanZaBrisanje == -1) {
            JOptionPane.showMessageDialog(this, "Molimo Vas da prvo izaberete korisnika za brisanje");
            return;
        }

        PotvrdaOBrisanju potvrdaOBrisanju = new PotvrdaOBrisanju(this, true);
        potvrdaOBrisanju.setVisible(true);

    }//GEN-LAST:event_btnObrisiClanaActionPerformed

    private void btnDodajNovogClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajNovogClanaActionPerformed

        DodajNovogClanaForma noviClan = new DodajNovogClanaForma(this, true);
        noviClan.pack();
        noviClan.setVisible(true);

    }//GEN-LAST:event_btnDodajNovogClanaActionPerformed

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed

        glavnaForma.setVisible(true);
        this.dispose();
        glavnaForma.getBtnPretragaClanova().setEnabled(true);
    }//GEN-LAST:event_btnNazadActionPerformed

    private void tblClanoviMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClanoviMouseClicked

        btnEvidentirajClanarinu.setEnabled(true);
        btnIzmeniPodatkeOClanu.setEnabled(true);
        btnObrisiClana.setEnabled(true);
        btnZaduzenja.setEnabled(true);
    }//GEN-LAST:event_tblClanoviMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        glavnaForma.setBrFormiClan(0);
        glavnaForma.getBtnPretragaClanova().setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    private void btnEvidentirajClanarinuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvidentirajClanarinuActionPerformed

        EvidentiranjeClanarine ec = new EvidentiranjeClanarine(this, true);
        ec.pack();
        ec.setVisible(true);

    }//GEN-LAST:event_btnEvidentirajClanarinuActionPerformed

    private void btnZaduzenjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaduzenjaActionPerformed

        int indeksClana = vratiIndeksSelektovanogClana();
        if (indeksClana == -1) {
            JOptionPane.showMessageDialog(this, "Molimo Vas da prvo izaberete korisnika za brisanje");
            return;
        }

        Clan clanZaduzenja = vratiSelektovanogClana(indeksClana);

        ZaduzenjaClanovaForma zcf = new ZaduzenjaClanovaForma(clanZaduzenja, ulogovaniRadnik);
        zcf.pack();
        zcf.setVisible(true);

    }//GEN-LAST:event_btnZaduzenjaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajNovogClana;
    private javax.swing.JButton btnEvidentirajClanarinu;
    private javax.swing.JButton btnIzmeniPodatkeOClanu;
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnObrisiClana;
    private javax.swing.JButton btnZaduzenja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClanovi;
    private javax.swing.JTextField txtPretragaClanova;
    // End of variables declaration//GEN-END:variables

    public ArrayList<Clan> vratiSveClanove() {

        KlijentskiZahtev klijentskiZahtev = new KlijentskiZahtev();
        klijentskiZahtev.setParametar(new Clan());
        klijentskiZahtev.setOperacija(Operacija.VRATI_KORISNIKE);

        Komunikacija.getInstanca().posaljiKlijentskiZahtev(klijentskiZahtev);
        ServerskiOdgovor serverskiOdgovor = Komunikacija.getInstanca().primiServerskiOdgovor();

        ArrayList<Clan> listaClanova = (ArrayList<Clan>) serverskiOdgovor.getOdgovor();

        return listaClanova;

    }

    public void popuniTabeluClanova() {

        listaClanova = this.vratiSveClanove();
        ModelTabeleClanova modelTabeleClanova = new ModelTabeleClanova(listaClanova);
        tblClanovi.setModel(modelTabeleClanova);

    }

    void ubaciNovogClana(Clan noviClan) {

        ModelTabeleClanova modelTabeleClanova = (ModelTabeleClanova) tblClanovi.getModel();
        modelTabeleClanova.dodajNovogClana(noviClan);

    }

    public Clan vratiSelektovanogClana(int clanZaBrisanjeIndeks) {

        ModelTabeleClanova modelTabeleClanova = (ModelTabeleClanova) tblClanovi.getModel();
        Clan clan = modelTabeleClanova.vratiSelektovanogClana(clanZaBrisanjeIndeks);
        return clan;

    }

    public Clan getIzmenjenClan() {
        return izmenjenClan;
    }

    public void setIzmenjenClan(Clan izmenjenClan) {
        this.izmenjenClan = izmenjenClan;
    }

    public javax.swing.JButton getBtnEvidentirajClanarinu() {
        return btnEvidentirajClanarinu;
    }

    public void setBtnEvidentirajClanarinu(javax.swing.JButton btnEvidentirajClanarinu) {
        this.btnEvidentirajClanarinu = btnEvidentirajClanarinu;
    }

    public javax.swing.JButton getBtnIzmeniPodatkeOClanu() {
        return btnIzmeniPodatkeOClanu;
    }

    public void setBtnIzmeniPodatkeOClanu(javax.swing.JButton btnIzmeniPodatkeOClanu) {
        this.btnIzmeniPodatkeOClanu = btnIzmeniPodatkeOClanu;
    }

    public javax.swing.JButton getBtnObrisiClana() {
        return btnObrisiClana;
    }

    public void setBtnObrisiClana(javax.swing.JButton btnObrisiClana) {
        this.btnObrisiClana = btnObrisiClana;
    }

    public Clan getNoviClan() {
        return noviClan;
    }

    public void setNoviClan(Clan noviClan) {
        this.noviClan = noviClan;
    }

    Radnik vratiUlogovanogRadnika() {
        return glavnaForma.getUlogovaniRadnik();
    }

    public Clanarina getEvidentiranaClanarina() {
        return evidentiranaClanarina;
    }

    public void setEvidentiranaClanarina(Clanarina evidentiranaClanarina) {
        this.evidentiranaClanarina = evidentiranaClanarina;
    }

    public Radnik getUlogovaniRadnik() {
        return ulogovaniRadnik;
    }

    public void setUlogovaniRadnik(Radnik ulogovaniRadnik) {
        this.ulogovaniRadnik = ulogovaniRadnik;
    }

    public javax.swing.JButton getBtnZaduzenja() {
        return btnZaduzenja;
    }

    public void setBtnZaduzenja(javax.swing.JButton btnZaduzenja) {
        this.btnZaduzenja = btnZaduzenja;
    }

}
