/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Clan;
import domen.Knjiga;
import domen.Primerak;

import forme.potvrde.PotvrdaOZaduzenju;
import java.awt.Dimension;

import java.awt.Toolkit;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import modeli.ModelTabeleClanova;

import operacije.Operacija;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author STEFAN94
 */
public class ClanoviZaZaduzenje extends javax.swing.JDialog {

    private ZaduzenjaForma zf;
    private Clan selektovniClan;
    private ArrayList<Clan> listaClanova;
    private int brojPrimeraka;

    /**
     * Creates new form ClanoviZaZaduzenje
     *
     * @param parent
     * @param modal
     */
    public ClanoviZaZaduzenje(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(java.awt.Color.lightGray);
        btnZaduzi.setEnabled(false);
        popuniTabeluClanova();
        zf = (ZaduzenjaForma) this.getParent();
        popuniCmbPrimeraka();
        brojPrimeraka = zf.getBrojSlobodnihPrimeraka();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblClanoviZaZaduzenje = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtPretragaClanova = new javax.swing.JTextField();
        btnZaduzi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbPrimerci = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clanovi sa vazecom clanarinom");

        tblClanoviZaZaduzenje.setBackground(new java.awt.Color(0, 102, 102));
        tblClanoviZaZaduzenje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClanoviZaZaduzenje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClanoviZaZaduzenjeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClanoviZaZaduzenje);

        jLabel1.setText("Pretraga clanova sa vazecom clanarinom(Ime/Prezime/JMBG):");

        txtPretragaClanova.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPretragaClanovaKeyReleased(evt);
            }
        });

        btnZaduzi.setText("Zaduzi clana");
        btnZaduzi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaduziActionPerformed(evt);
            }
        });

        jLabel2.setText("Raspolozivi primerci:");

        cmbPrimerci.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPretragaClanova)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cmbPrimerci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnZaduzi)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPretragaClanova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cmbPrimerci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnZaduzi))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZaduziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaduziActionPerformed

        zf.azurirajBrPrimeraka();
        brojPrimeraka = zf.getBrojSlobodnihPrimeraka();
        if (brojPrimeraka > 0) {
            int indeks = tblClanoviZaZaduzenje.getSelectedRow();
            ModelTabeleClanova mtc = (ModelTabeleClanova) tblClanoviZaZaduzenje.getModel();
            selektovniClan = mtc.vratiSelektovanogClana(indeks);
            zf.setSelektovanClanZaZaduzenje(selektovniClan);
            Primerak selektovaniPrimerak = (Primerak) cmbPrimerci.getSelectedItem();
            zf.setSelektovaniPrimerak(selektovaniPrimerak);
            PotvrdaOZaduzenju poz = new PotvrdaOZaduzenju(zf, true);
            poz.setCzz(this);
            poz.pack();
            poz.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Nema vise slobodnih primeraka");
            return;
        }
        brojPrimeraka = zf.getBrojSlobodnihPrimeraka();


    }//GEN-LAST:event_btnZaduziActionPerformed

    private void txtPretragaClanovaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretragaClanovaKeyReleased

        String pretraga = txtPretragaClanova.getText().trim();
        Clan clan = new Clan();
        clan.setIme(pretraga);
        clan.setPrezime(pretraga);
        long jmbg =0;
        try {
            jmbg = Long.parseLong(pretraga);
        } catch (Exception e) {
            jmbg = 0;
        }
        clan.setJmbg(jmbg);
        KlijentskiZahtev klijentskiZahtev = new KlijentskiZahtev();
        klijentskiZahtev.setOperacija(Operacija.PRETRAZI_CLANOVE);
        klijentskiZahtev.setParametar(clan);

        Komunikacija.getInstanca().posaljiKlijentskiZahtev(klijentskiZahtev);
        ServerskiOdgovor serverskiOdgovor = Komunikacija.getInstanca().primiServerskiOdgovor();

        ArrayList<Clan> listaClanova = (ArrayList<Clan>) serverskiOdgovor.getOdgovor();
        
        btnZaduzi.setEnabled(false);
        ModelTabeleClanova modelTabeleClanova = (ModelTabeleClanova) tblClanoviZaZaduzenje.getModel();
        modelTabeleClanova.azurirajTabelu(listaClanova);
        
//        String pretraga = txtPretragaClanova.getText();
//        String patternZaPretragu = "^" + pretraga + ".*".toLowerCase();
//        ArrayList<Clan> listaPretrazenihClanova = new ArrayList<>();
//        for (Clan clan : listaClanova) {
//
//            String jmbgString = clan.getJmbg() + "";
//
//            if (clan.getIme().toLowerCase().matches(patternZaPretragu)
//                    || clan.getPrezime().toLowerCase().matches(patternZaPretragu)
//                    || clan.getIme().concat(" ").concat(clan.getPrezime()).toLowerCase().matches(patternZaPretragu)
//                    || clan.getPrezime().concat(" ").concat(clan.getIme()).toLowerCase().matches(patternZaPretragu)
//                    || jmbgString.matches(patternZaPretragu)) {
//                listaPretrazenihClanova.add(clan);
//            }
//        }
//
//        ModelTabeleClanova mtc = (ModelTabeleClanova) tblClanoviZaZaduzenje.getModel();
//        mtc.azurirajTabelu(listaPretrazenihClanova);
//
//        System.out.println("Izvrsilo se!");

    }//GEN-LAST:event_txtPretragaClanovaKeyReleased

    private void tblClanoviZaZaduzenjeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClanoviZaZaduzenjeMouseClicked

        btnZaduzi.setEnabled(true);

    }//GEN-LAST:event_tblClanoviZaZaduzenjeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClanoviZaZaduzenje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClanoviZaZaduzenje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClanoviZaZaduzenje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClanoviZaZaduzenje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ClanoviZaZaduzenje dialog = new ClanoviZaZaduzenje(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public ArrayList<Clan> vratiSveClanoveSaClanarinom() {

        KlijentskiZahtev klijentskiZahtev = new KlijentskiZahtev();
        klijentskiZahtev.setOperacija(Operacija.VRATI_CLANOVE_SA_VAZECOM_CLANARINOM);

        Komunikacija.getInstanca().posaljiKlijentskiZahtev(klijentskiZahtev);
        ServerskiOdgovor serverskiOdgovor = Komunikacija.getInstanca().primiServerskiOdgovor();

        ArrayList<Clan> listaClanova = (ArrayList<Clan>) serverskiOdgovor.getOdgovor();

        return listaClanova;

    }

    public void popuniTabeluClanova() {

        listaClanova = this.vratiSveClanoveSaClanarinom();
        ModelTabeleClanova modelTabeleClanova = new ModelTabeleClanova(listaClanova);
        tblClanoviZaZaduzenje.setModel(modelTabeleClanova);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnZaduzi;
    private javax.swing.JComboBox cmbPrimerci;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClanoviZaZaduzenje;
    private javax.swing.JTextField txtPretragaClanova;
    // End of variables declaration//GEN-END:variables

    public Clan getSelektovniClan() {
        return selektovniClan;
    }

    public void setSelektovniClan(Clan selektovniClan) {
        this.selektovniClan = selektovniClan;
    }

    public int getBrojPrimeraka() {
        return brojPrimeraka;
    }

    public void setBrojPrimeraka(int brojPrimeraka) {
        this.brojPrimeraka = brojPrimeraka;
    }

    public javax.swing.JButton getBtnZaduzi() {
        return btnZaduzi;
    }

    public void setBtnZaduzi(javax.swing.JButton btnZaduzi) {
        this.btnZaduzi = btnZaduzi;
    }

    public void popuniCmbPrimeraka() {
        Knjiga selektovanaKnjiga = zf.getSelektovanaKnjiga();
        Primerak p = new Primerak();
        p.setIsbn(selektovanaKnjiga.getIsbn());
        ArrayList<Primerak> listaSlobodnihPrimeraka = new ArrayList<>();
        for (Primerak primerak : vratiPrimerkeZaSelektovanuKnjigu(p)) {
            if (!primerak.isZaduzen() && !primerak.isRashodovan()) {
                listaSlobodnihPrimeraka.add(primerak);
            }
        }
        cmbPrimerci.removeAllItems();
        for (Primerak primerak : listaSlobodnihPrimeraka) {
            cmbPrimerci.addItem(primerak);
        }
        if (listaSlobodnihPrimeraka.isEmpty()) {
            cmbPrimerci.setVisible(false);
        }
    }

    private ArrayList<Primerak> vratiPrimerkeZaSelektovanuKnjigu(Primerak primerak) {

        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacija.VRATI_PRIMERKE);
        kz.setParametar(primerak);

        Komunikacija.getInstanca().posaljiKlijentskiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstanca().primiServerskiOdgovor();
        ArrayList<Primerak> listaPrimeraka = (ArrayList<Primerak>) so.getOdgovor();
        return listaPrimeraka;

    }

    public javax.swing.JComboBox getCmbPrimerci() {
        return cmbPrimerci;
    }

    public void setCmbPrimerci(javax.swing.JComboBox cmbPrimerci) {
        this.cmbPrimerci = cmbPrimerci;
    }
}
