/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Clan;
import domen.Clanarina;
import domen.Radnik;
import forme.potvrde.PotvrdaOEvidencijiClanarine;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import niti.NitOsluskujEvidentiranjeClanarine;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author STEFAN94
 */
public class EvidentiranjeClanarine extends javax.swing.JDialog {

    private Clan selektovaniClan;
    private Clanarina c;

    /**
     * Creates new form EvidentiranjeClanarine
     *
     * @param parent
     * @param modal
     */
    public EvidentiranjeClanarine(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(java.awt.Color.lightGray);
        vratiPodatke();
        spnBrojMeseci.setValue(1);
        NitOsluskujEvidentiranjeClanarine noec = new NitOsluskujEvidentiranjeClanarine(this);
        noec.start();
        
        Dimension screenSize, frameSize;
        int x, y;
        screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        frameSize = getSize();
        x = (screenSize.width - frameSize.width) / 2;
        y = (screenSize.height - frameSize.height) / 2;
        setLocation(x, y);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblClan = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCena = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        spnBrojMeseci = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        btnEvidentiraj = new javax.swing.JButton();
        btnOdustani = new javax.swing.JButton();
        lblDatum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Evidencija clanarine");

        jLabel1.setText("Clan:");

        lblClan.setText("jLabel2");

        jLabel3.setText("Cena:");

        jLabel4.setText("Broj meseci:");

        jLabel5.setText("Clanarina vazi do:");

        btnEvidentiraj.setText("Evidentiraj");
        btnEvidentiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvidentirajActionPerformed(evt);
            }
        });

        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        lblDatum.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEvidentiraj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(btnOdustani))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblClan)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCena)
                            .addComponent(spnBrojMeseci)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lblDatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblClan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblDatum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spnBrojMeseci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEvidentiraj)
                    .addComponent(btnOdustani))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
       
        dispose();
        
    }//GEN-LAST:event_btnOdustaniActionPerformed

    private void btnEvidentirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvidentirajActionPerformed

        double cena = 0.0;
        try {
            cena = Double.parseDouble(txtCena.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Molimo Vas da unosite validne vrednosti za cenu");
            return;
        }

        int brMeseci = 0;
        if ((int) spnBrojMeseci.getValue() < 1) {
            JOptionPane.showMessageDialog(this, "Evidentiranje clanarine mora biti za bar jedan mesec");
            return;
        }

        brMeseci = (int) spnBrojMeseci.getValue();

        Date datumOd = new Date();
        Calendar kalendar = Calendar.getInstance();
        if (c == null) {
            kalendar.setTime(datumOd);
            kalendar.add(Calendar.MONTH, brMeseci);
        } else {
            if (c.getDatumDo().before(datumOd) || c.getDatumDo() == null) {
                kalendar.setTime(datumOd);
                kalendar.add(Calendar.MONTH, brMeseci);
            } else {
                datumOd = c.getDatumDo();
                kalendar.setTime(c.getDatumDo());
                kalendar.add(Calendar.MONTH, brMeseci);
            }
        }

        Date datumNoveClanarine = kalendar.getTime();
        ClanoviForma cf = (ClanoviForma) this.getParent();
        Radnik radnik = cf.vratiUlogovanogRadnika();
        Clanarina novaClanarina = new Clanarina(-1, datumOd, datumNoveClanarine, cena, radnik, selektovaniClan);
        cf.setEvidentiranaClanarina(novaClanarina);
        PotvrdaOEvidencijiClanarine poec = new PotvrdaOEvidencijiClanarine(cf, true);
        poec.setEc(this);
        poec.pack();
        poec.setVisible(true);

    }//GEN-LAST:event_btnEvidentirajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EvidentiranjeClanarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EvidentiranjeClanarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EvidentiranjeClanarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EvidentiranjeClanarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EvidentiranjeClanarine dialog = new EvidentiranjeClanarine(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEvidentiraj;
    private javax.swing.JButton btnOdustani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblClan;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JSpinner spnBrojMeseci;
    private javax.swing.JTextField txtCena;
    // End of variables declaration//GEN-END:variables

    public void vratiPodatke() {
        ClanoviForma cf = (ClanoviForma) this.getParent();
        int indeksSelektovanogClana = cf.vratiIndeksSelektovanogClana();
        selektovaniClan = cf.vratiSelektovanogClana(indeksSelektovanogClana);
        lblClan.setText(selektovaniClan.getIme() + " " + selektovaniClan.getPrezime());

        KlijentskiZahtev kz = new KlijentskiZahtev();
        Clanarina cl = new Clanarina();
        cl.setClan(selektovaniClan);
        kz.setParametar(cl);
        kz.setOperacija(operacije.Operacija.VRATI_CLANARINU);

        komunikacija.Komunikacija.getInstanca().posaljiKlijentskiZahtev(kz);
        ServerskiOdgovor so = komunikacija.Komunikacija.getInstanca().primiServerskiOdgovor();

        c = (Clanarina) so.getOdgovor();
        if (c == null) {
            lblDatum.setText("Nema podataka o clanarini");
            return;
        }
        Date sadasnjiDatun = new Date();
        if (c.getDatumDo().before(sadasnjiDatun)) {
            lblDatum.setText("Clanarina je istekal");
        } else {
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
            String datumString = sdf.format(c.getDatumDo());
            lblDatum.setText(datumString);
        }
    }


    public javax.swing.JLabel getLblDatum() {
        return lblDatum;
    }

    public void setLblDatum(javax.swing.JLabel lblDatum) {
        this.lblDatum = lblDatum;
    }

    public javax.swing.JSpinner getSpnBrojMeseci() {
        return spnBrojMeseci;
    }

    public void setSpnBrojMeseci(javax.swing.JSpinner spnBrojMeseci) {
        this.spnBrojMeseci = spnBrojMeseci;
    }

    public javax.swing.JTextField getTxtCena() {
        return txtCena;
    }

    public void setTxtCena(javax.swing.JTextField txtCena) {
        this.txtCena = txtCena;
    }

    public javax.swing.JButton getBtnEvidentiraj() {
        return btnEvidentiraj;
    }

    public void setBtnEvidentiraj(javax.swing.JButton btnEvidentiraj) {
        this.btnEvidentiraj = btnEvidentiraj;
    }

}
