/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import forme.potvrde.PotvrdaOBrisanjuKnjige;
import domen.Knjiga;
import domen.Radnik;

import java.awt.Dialog;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import modeli.ModelTabeleKnjiga;

import operacije.Operacija;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author STEFAN94
 */
public class GlavnaForma extends javax.swing.JFrame {

    private Radnik ulogovaniRadnik;
    private Knjiga izmenjenaKnjiga;
    private Knjiga novaKnjiga;
    private int brFormiClan;
    private ArrayList<Knjiga> listaKnjiga;

    
    /**
     * Creates new form GlavnaForma
     *
     * @param ulogovaniRadnik
     */
    public GlavnaForma(Radnik ulogovaniRadnik) {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.getContentPane().setBackground(java.awt.Color.lightGray);
        initComponents();
        this.ulogovaniRadnik = ulogovaniRadnik;
        popuniTabeluKnjiga();
        popuniCombobox();
        brFormiClan = 0;
        btnIzmeni.setEnabled(false);
        btnObrisi.setEnabled(false);
        btnZaduziKnjigu.setEnabled(false);
        this.setTitle("Ulogovani radnik: " + ulogovaniRadnik.getIme() + " " + ulogovaniRadnik.getPrezime());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtKnjige = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKnjige = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnPretragaClanova = new javax.swing.JButton();
        cmbZanrovi = new javax.swing.JComboBox<>();
        btnIzmeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnUbaciNovuKnjigu = new javax.swing.JButton();
        btnZaduziKnjigu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setText("Pretraga clanova:");

        txtKnjige.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKnjigeKeyReleased(evt);
            }
        });

        jLabel3.setText("Pretraga knjiga(Naziv/Pisac/ISBN):");

        tblKnjige.setBackground(new java.awt.Color(0, 102, 102));
        tblKnjige.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKnjige.setSelectionForeground(new java.awt.Color(0, 153, 153));
        tblKnjige.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKnjigeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKnjige);

        jLabel4.setText("Lista knjiga:");

        btnPretragaClanova.setText("Pretraga clanova");
        btnPretragaClanova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaClanovaActionPerformed(evt);
            }
        });

        cmbZanrovi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbZanrovi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbZanroviItemStateChanged(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnUbaciNovuKnjigu.setText("Unesi novu knjigu");
        btnUbaciNovuKnjigu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbaciNovuKnjiguActionPerformed(evt);
            }
        });

        btnZaduziKnjigu.setText("Zaduzi knjigu");
        btnZaduziKnjigu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaduziKnjiguActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUbaciNovuKnjigu)
                        .addGap(28, 28, 28)
                        .addComponent(btnIzmeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnObrisi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnZaduziKnjigu))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtKnjige, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbZanrovi, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 400, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPretragaClanova)
                            .addComponent(jLabel1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKnjige, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbZanrovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretragaClanova))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUbaciNovuKnjigu)
                    .addComponent(btnIzmeni)
                    .addComponent(btnObrisi)
                    .addComponent(btnZaduziKnjigu)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretragaClanovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaClanovaActionPerformed

        if (brFormiClan <= 1) {
            ClanoviForma clanoviForma = new ClanoviForma(this);
            clanoviForma.pack();
            clanoviForma.setVisible(true);
            clanoviForma.setModalExclusionType(Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
            brFormiClan++;
        }


    }//GEN-LAST:event_btnPretragaClanovaActionPerformed

    private void txtKnjigeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKnjigeKeyReleased

        String naziv = txtKnjige.getText().trim();
        String isbn = txtKnjige.getText();
        String pisac = txtKnjige.getText();
        String zanr = (String) cmbZanrovi.getSelectedItem();
        Knjiga knjigaZaPretragu = new Knjiga();
        knjigaZaPretragu.setNaziv(naziv);
        knjigaZaPretragu.setIsbn(isbn);
        knjigaZaPretragu.setPisac(pisac);
        knjigaZaPretragu.setZanr(zanr);

        KlijentskiZahtev klijentskiZahtev = new KlijentskiZahtev();
        klijentskiZahtev.setOperacija(Operacija.PRETRAZI_KNJIGE);
        klijentskiZahtev.setParametar(knjigaZaPretragu);

        Komunikacija.getInstanca().posaljiKlijentskiZahtev(klijentskiZahtev);
        ServerskiOdgovor serverskiOdgovor = Komunikacija.getInstanca().primiServerskiOdgovor();

        listaKnjiga = (ArrayList<Knjiga>) serverskiOdgovor.getOdgovor();

        Object[][] rows = popuniRedove(listaKnjiga);

        ModelTabeleKnjiga modelTabeleKnjiga = (ModelTabeleKnjiga) tblKnjige.getModel();
        modelTabeleKnjiga.azurirajTabelu(rows);

        btnIzmeni.setEnabled(false);
        btnObrisi.setEnabled(false);
        btnZaduziKnjigu.setEnabled(false);
    }//GEN-LAST:event_txtKnjigeKeyReleased

    private void btnZaduziKnjiguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaduziKnjiguActionPerformed

        ZaduzenjaForma zf = new ZaduzenjaForma(this);
        zf.pack();
        zf.setVisible(true);

    }//GEN-LAST:event_btnZaduziKnjiguActionPerformed

    private void btnUbaciNovuKnjiguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbaciNovuKnjiguActionPerformed

        UnesiNovuKnjiguForma unesiNovuKnjiguForma = new UnesiNovuKnjiguForma(this, true);
        unesiNovuKnjiguForma.pack();
        unesiNovuKnjiguForma.setVisible(true);

    }//GEN-LAST:event_btnUbaciNovuKnjiguActionPerformed

    public int vratiIndeksSelektovaneKnjige() {

        return tblKnjige.getSelectedRow();

    }

    public Knjiga vratiSelektovanuKnjigu(int indeks) {

        ModelTabeleKnjiga modelTabeleKnjiga = (ModelTabeleKnjiga) tblKnjige.getModel();
        Knjiga knjiga = null;
        try {
            knjiga = modelTabeleKnjiga.vratiKnjigu(indeks);
        } catch (IOException ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
        return knjiga;

    }

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed

        int knjigaZaBrisanje = vratiIndeksSelektovaneKnjige();

        if (knjigaZaBrisanje == -1) {
            JOptionPane.showMessageDialog(this, "Molimo Vas da prvo selektujete knjigu za brisanje");
            return;
        }

        PotvrdaOBrisanjuKnjige potvrdaOBrisanjuKnjige = new PotvrdaOBrisanjuKnjige(this, true);
        potvrdaOBrisanjuKnjige.pack();
        potvrdaOBrisanjuKnjige.setVisible(true);


    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed

        IzmeniPodatkeOKnjiziForma izmeniPodatkeOKnjiziForma = new IzmeniPodatkeOKnjiziForma(this, true);
        izmeniPodatkeOKnjiziForma.pack();
        izmeniPodatkeOKnjiziForma.setVisible(true);

    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void cmbZanroviItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbZanroviItemStateChanged

        String zanr = (String) cmbZanrovi.getSelectedItem();
        if (zanr != null) {

            String pretraga = txtKnjige.getText().trim();
            Knjiga knjigaZaPretragu = new Knjiga();
            knjigaZaPretragu.setNaziv(pretraga);
            knjigaZaPretragu.setIsbn(pretraga);
            knjigaZaPretragu.setPisac(pretraga);
            knjigaZaPretragu.setZanr(zanr);
            KlijentskiZahtev klijentskiZahtev = new KlijentskiZahtev();
            klijentskiZahtev.setOperacija(Operacija.PRETRAZI_KNJIGE);
            klijentskiZahtev.setParametar(knjigaZaPretragu);

            Komunikacija.getInstanca().posaljiKlijentskiZahtev(klijentskiZahtev);
            ServerskiOdgovor serverskiOdgovor = Komunikacija.getInstanca().primiServerskiOdgovor();

            listaKnjiga = (ArrayList<Knjiga>) serverskiOdgovor.getOdgovor();
            Object[][] rows = popuniRedove(listaKnjiga);

            ModelTabeleKnjiga modelTabeleKnjiga = (ModelTabeleKnjiga) tblKnjige.getModel();
            modelTabeleKnjiga.azurirajTabelu(rows);
        }
    }//GEN-LAST:event_cmbZanroviItemStateChanged

    private void tblKnjigeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKnjigeMouseClicked

        btnIzmeni.setEnabled(true);
        btnObrisi.setEnabled(true);
        btnZaduziKnjigu.setEnabled(true);

    }//GEN-LAST:event_tblKnjigeMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPretragaClanova;
    private javax.swing.JButton btnUbaciNovuKnjigu;
    private javax.swing.JButton btnZaduziKnjigu;
    private javax.swing.JComboBox<String> cmbZanrovi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblKnjige;
    private javax.swing.JTextField txtKnjige;
    // End of variables declaration//GEN-END:variables

    public void popuniTabeluKnjiga() {

        KlijentskiZahtev klijentskiZahtev = new KlijentskiZahtev();
        klijentskiZahtev.setParametar(new Knjiga());
        klijentskiZahtev.setOperacija(Operacija.VRATI_KNJIGE);

        Komunikacija.getInstanca().posaljiKlijentskiZahtev(klijentskiZahtev);

        ServerskiOdgovor serverskiOdgovor = Komunikacija.getInstanca().primiServerskiOdgovor();

        listaKnjiga = (ArrayList<Knjiga>) serverskiOdgovor.getOdgovor();
        String[] columnName = {"ISBN", "Naziv", "Pisac", "Godina izdanja", "Pismo", "Broj strana", "Zanr", "Povez", "Slika"};
        Object[][] rows = popuniRedove(listaKnjiga);

        ModelTabeleKnjiga modelTabeleKnjiga = new ModelTabeleKnjiga(columnName, rows);

        tblKnjige.setModel(modelTabeleKnjiga);
        tblKnjige.setRowHeight(150);
        tblKnjige.getColumnModel().getColumn(8).setPreferredWidth(100);

    }

    private Object[][] popuniRedove(ArrayList<Knjiga> listaKnjiga) {
        Object[][] rows = new Object[listaKnjiga.size()][10];
        for (int i = 0; i < listaKnjiga.size(); i++) {
            rows[i][0] = listaKnjiga.get(i).getIsbn();
            rows[i][1] = listaKnjiga.get(i).getNaziv();
            rows[i][2] = listaKnjiga.get(i).getPisac();
            rows[i][3] = listaKnjiga.get(i).getGodinaIzdanja();
            rows[i][4] = listaKnjiga.get(i).getPismo();
            rows[i][5] = listaKnjiga.get(i).getBrojStrana();
            rows[i][6] = listaKnjiga.get(i).getZanr();
            rows[i][7] = listaKnjiga.get(i).getPovez();

            if (listaKnjiga.get(i).getSlika() != null) {
                ImageIcon image = new ImageIcon(new ImageIcon(listaKnjiga.get(i).getSlika()).getImage().getScaledInstance(100, 150, Image.SCALE_SMOOTH));

                rows[i][8] = image;
            } else {
                rows[i][8] = null;
            }
            rows[i][9] = listaKnjiga.get(i).getListaPrimeraka();

        }
        return rows;
    }

    private void popuniCombobox() {

        String[] zanrovi = Knjiga.LISTA_ZANROVA;
        cmbZanrovi.removeAllItems();
        cmbZanrovi.addItem("Svi zanrovi");
        for (int i = 0; i < zanrovi.length; i++) {
            cmbZanrovi.addItem(zanrovi[i]);
        }

    }

    public Knjiga getIzmenjenaKnjiga() {
        return izmenjenaKnjiga;
    }

    public void setIzmenjenaKnjiga(Knjiga izmenjenaKnjiga) {
        this.izmenjenaKnjiga = izmenjenaKnjiga;
    }

    public Knjiga getNovaKnjiga() {
        return novaKnjiga;
    }

    public void setNovaKnjiga(Knjiga novaKnjiga) {
        this.novaKnjiga = novaKnjiga;
    }

    public javax.swing.JButton getBtnIzmeni() {
        return btnIzmeni;
    }

    public void setBtnIzmeni(javax.swing.JButton btnIzmeni) {
        this.btnIzmeni = btnIzmeni;
    }

    public javax.swing.JButton getBtnObrisi() {
        return btnObrisi;
    }

    public void setBtnObrisi(javax.swing.JButton btnObrisi) {
        this.btnObrisi = btnObrisi;
    }

    public javax.swing.JButton getBtnZaduziKnjigu() {
        return btnZaduziKnjigu;
    }

    public void setBtnZaduziKnjigu(javax.swing.JButton btnZaduziKnjigu) {
        this.btnZaduziKnjigu = btnZaduziKnjigu;
    }

    public javax.swing.JButton getBtnPretragaClanova() {
        return btnPretragaClanova;
    }

    public void setBtnPretragaClanova(javax.swing.JButton btnPretragaClanova) {
        this.btnPretragaClanova = btnPretragaClanova;
    }

    public int getBrFormiClan() {
        return brFormiClan;
    }

    public void setBrFormiClan(int brFormiClan) {
        this.brFormiClan = brFormiClan;
    }

    public Radnik getUlogovaniRadnik() {
        return ulogovaniRadnik;
    }

    public void setUlogovaniRadnik(Radnik ulogovaniRadnik) {
        this.ulogovaniRadnik = ulogovaniRadnik;
    }

    public javax.swing.JButton getBtnUbaciNovuKnjigu() {
        return btnUbaciNovuKnjigu;
    }

    public void setBtnUbaciNovuKnjigu(javax.swing.JButton btnUbaciNovuKnjigu) {
        this.btnUbaciNovuKnjigu = btnUbaciNovuKnjigu;
    }

    public ArrayList<Knjiga> getListaKnjiga() {
        return listaKnjiga;
    }

    public void setListaKnjiga(ArrayList<Knjiga> listaKnjiga) {
        this.listaKnjiga = listaKnjiga;
    }

}
