/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Clan;
import domen.Knjiga;
import domen.Primerak;
import domen.Radnik;
import domen.Zaduzenje;
import forme.potvrde.PotvrdaOZaduzivanjuClana;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import modeli.ModelTabeleKnjiga;
import operacije.Operacija;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author STEFAN94
 */
public class KnjigeZaZaduzenje extends javax.swing.JDialog {

    private ArrayList<Knjiga> listaKnjiga;
    private ZaduzenjaClanovaForma zcf;
    private Clan selektovaniClan;
    private Zaduzenje zaduzenje;
    private Knjiga selektovanaKnjiga;
    private Radnik ulogovaniRadnik;
    private int brojSlobodnihPrimeraka;
    private ArrayList<Primerak> listaPrimeraka = new ArrayList<>();
    private Primerak selektovaniPrimerak;

    /**
     * Creates new form KnjigeZaZaduzenje
     *
     * @param parent
     * @param modal
     */
    public KnjigeZaZaduzenje(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        zcf = (ZaduzenjaClanovaForma) this.getParent();
        initComponents();
        this.getContentPane().setBackground(java.awt.Color.lightGray);
        lblBrojPrimeraka.setVisible(false);
        cmbPrimerci.setVisible(false);
        selektovaniClan = zcf.getClanZaduzenja();
        zaduzenje = zcf.getSelektovanoZaduzenje();
        ulogovaniRadnik = zcf.getUlogovaniRadnik();
        listaKnjiga = new ArrayList<>();
        popuniTabelu();
        popuniCombobox();
//        popuniComboboxPrimeraka();
        lblClan.setText("Zaduzivanje clana: " + selektovaniClan.getIme() + " " + selektovaniClan.getPrezime());
        btnZaduzi.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtKnjige = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKnjige = new javax.swing.JTable();
        btnZaduzi = new javax.swing.JButton();
        lblClan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblBrojPrimeraka = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbPrimerci = new javax.swing.JComboBox();
        cmbZanrovi = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Knjige za zaduzenje");

        jLabel1.setText("Pretraga knjiga(Naziv/Pisac/ISBN):");

        txtKnjige.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKnjigeKeyReleased(evt);
            }
        });

        tblKnjige.setBackground(new java.awt.Color(0, 102, 102));
        tblKnjige.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKnjige.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKnjigeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKnjige);

        btnZaduzi.setText("Novo zaduzenje");
        btnZaduzi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaduziActionPerformed(evt);
            }
        });

        lblClan.setText("jLabel2");

        jLabel2.setText("Broj slobodnih primeraka:");

        lblBrojPrimeraka.setText("jLabel3");

        jLabel3.setText("Raspolozivi primerci:");

        cmbPrimerci.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbZanrovi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbZanrovi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbZanroviItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKnjige, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(lblClan))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnZaduzi))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cmbZanrovi, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblBrojPrimeraka)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cmbPrimerci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 145, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKnjige, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbZanrovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClan)
                    .addComponent(jLabel2)
                    .addComponent(lblBrojPrimeraka)
                    .addComponent(jLabel3)
                    .addComponent(cmbPrimerci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnZaduzi))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKnjigeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKnjigeKeyReleased

        String pretraga = txtKnjige.getText().trim();
        String zanr = (String) cmbZanrovi.getSelectedItem();
        Knjiga knjigaZaPretragu = new Knjiga();
        knjigaZaPretragu.setNaziv(pretraga);
        knjigaZaPretragu.setIsbn(pretraga);
        knjigaZaPretragu.setPisac(pretraga);
        knjigaZaPretragu.setZanr(zanr);
        KlijentskiZahtev klijentskiZahtev = new KlijentskiZahtev();
        klijentskiZahtev.setOperacija(Operacija.PRETRAZI_KNJIGE);
        klijentskiZahtev.setParametar(knjigaZaPretragu);

        Komunikacija.getInstanca().posaljiKlijentskiZahtev(klijentskiZahtev);
        ServerskiOdgovor serverskiOdgovor = Komunikacija.getInstanca().primiServerskiOdgovor();

        ArrayList<Knjiga> listaKnjiga = (ArrayList<Knjiga>) serverskiOdgovor.getOdgovor();

        Object[][] rows = popuniRedove(listaKnjiga);

        ModelTabeleKnjiga modelTabeleKnjiga = (ModelTabeleKnjiga) tblKnjige.getModel();
        modelTabeleKnjiga.azurirajTabelu(rows);
        lblBrojPrimeraka.setVisible(false);
        cmbPrimerci.setVisible(false);
        btnZaduzi.setEnabled(false);
 


    }//GEN-LAST:event_txtKnjigeKeyReleased

    private void tblKnjigeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKnjigeMouseClicked

        int indeksSelektovaneKnjige = vratiIndeksSelektovaneKnjige();
        selektovanaKnjiga = vratiSelektovanuKnjigu(indeksSelektovaneKnjige);
        brojSlobodnihPrimeraka = vratiBrojSlobodnihPrimeraka(selektovanaKnjiga);
        cmbPrimerci.setVisible(true);
        popuniComboboxPrimeraka();
        lblBrojPrimeraka.setText("" + brojSlobodnihPrimeraka);
        lblBrojPrimeraka.setVisible(true);
        btnZaduzi.setEnabled(true);

    }//GEN-LAST:event_tblKnjigeMouseClicked

    private void btnZaduziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaduziActionPerformed

        int indeksSelektovaneKnjige = vratiIndeksSelektovaneKnjige();
        selektovanaKnjiga = vratiSelektovanuKnjigu(indeksSelektovaneKnjige);
        listaPrimeraka = vratiPrimerkeZaSelektovanuKnjigu(selektovanaKnjiga);
        zcf.setListaPrimeraka(listaPrimeraka);
        zcf.setSelektovanaKnjiga(selektovanaKnjiga);
        int brojPrimeraka = vratiBrojSlobodnihPrimeraka(selektovanaKnjiga);
        selektovaniPrimerak = (Primerak) cmbPrimerci.getSelectedItem();
        zcf.setSelektovaniPrimerak(selektovaniPrimerak);
        System.out.println("br: " + brojPrimeraka);
        if (brojPrimeraka > 0) {
            PotvrdaOZaduzivanjuClana pozc = new PotvrdaOZaduzivanjuClana(zcf, true);
            pozc.setKzz(this);
            pozc.pack();
            pozc.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Nema slobodnih primeraka za datu knjigu");
            return;
        }

    }//GEN-LAST:event_btnZaduziActionPerformed

    private void cmbZanroviItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbZanroviItemStateChanged

                String zanr = (String) cmbZanrovi.getSelectedItem();
        if (zanr != null) {

            String pretraga = txtKnjige.getText().trim();
            Knjiga knjigaZaPretragu = new Knjiga();
            knjigaZaPretragu.setNaziv(pretraga);
            knjigaZaPretragu.setIsbn(pretraga);
            knjigaZaPretragu.setPisac(pretraga);
            knjigaZaPretragu.setZanr(zanr);
            KlijentskiZahtev klijentskiZahtev = new KlijentskiZahtev();
            klijentskiZahtev.setOperacija(Operacija.PRETRAZI_KNJIGE);
            klijentskiZahtev.setParametar(knjigaZaPretragu);

            Komunikacija.getInstanca().posaljiKlijentskiZahtev(klijentskiZahtev);
            ServerskiOdgovor serverskiOdgovor = Komunikacija.getInstanca().primiServerskiOdgovor();

            listaKnjiga = (ArrayList<Knjiga>) serverskiOdgovor.getOdgovor();
            Object[][] rows = popuniRedove(listaKnjiga);

            ModelTabeleKnjiga modelTabeleKnjiga = (ModelTabeleKnjiga) tblKnjige.getModel();
            modelTabeleKnjiga.azurirajTabelu(rows);
        }
    }//GEN-LAST:event_cmbZanroviItemStateChanged

    public void brojPrimeraka() {

        int indeksSelektovaneKnjige = vratiIndeksSelektovaneKnjige();
        selektovanaKnjiga = vratiSelektovanuKnjigu(indeksSelektovaneKnjige);
        Primerak p = new Primerak();
        p.setIsbn(selektovanaKnjiga.getIsbn());
        brojSlobodnihPrimeraka = vratiBrojSlobodnihPrimeraka(selektovanaKnjiga);
        lblBrojPrimeraka.setText("" + brojSlobodnihPrimeraka);
        lblBrojPrimeraka.setVisible(true);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KnjigeZaZaduzenje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KnjigeZaZaduzenje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KnjigeZaZaduzenje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KnjigeZaZaduzenje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KnjigeZaZaduzenje dialog = new KnjigeZaZaduzenje(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnZaduzi;
    private javax.swing.JComboBox cmbPrimerci;
    private javax.swing.JComboBox<String> cmbZanrovi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBrojPrimeraka;
    private javax.swing.JLabel lblClan;
    private javax.swing.JTable tblKnjige;
    private javax.swing.JTextField txtKnjige;
    // End of variables declaration//GEN-END:variables

    private void popuniTabelu() {

        KlijentskiZahtev klijentskiZahtev = new KlijentskiZahtev();
        klijentskiZahtev.setParametar(new Knjiga());
        klijentskiZahtev.setOperacija(Operacija.VRATI_KNJIGE);

        Komunikacija.getInstanca().posaljiKlijentskiZahtev(klijentskiZahtev);

        ServerskiOdgovor serverskiOdgovor = Komunikacija.getInstanca().primiServerskiOdgovor();

        listaKnjiga = (ArrayList<Knjiga>) serverskiOdgovor.getOdgovor();
        String[] columnName = {"ISBN", "Naziv", "Pisac", "Godina izdanja", "Pismo", "Broj strana", "Zanr", "Povez", "Slika"};
        Object[][] rows = popuniRedove(listaKnjiga);

        ModelTabeleKnjiga modelTabeleKnjiga = new ModelTabeleKnjiga(columnName, rows);

        tblKnjige.setModel(modelTabeleKnjiga);
        tblKnjige.setRowHeight(150);
        tblKnjige.getColumnModel().getColumn(8).setPreferredWidth(100);
    }

    private void popuniCombobox() {

        String[] zanrovi = Knjiga.LISTA_ZANROVA;
        cmbZanrovi.removeAllItems();
        cmbZanrovi.addItem("Svi zanrovi");
        for (int i = 0; i < zanrovi.length; i++) {
            cmbZanrovi.addItem(zanrovi[i]);
        }
    }

    public ArrayList<Primerak> vratiPrimerkeZaSelektovanuKnjigu(Knjiga selektovanaKnjiga) {
        Primerak p = new Primerak();
        p.setIsbn(selektovanaKnjiga.getIsbn());
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacija.VRATI_PRIMERKE);
        kz.setParametar(p);

        Komunikacija.getInstanca().posaljiKlijentskiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstanca().primiServerskiOdgovor();
        ArrayList<Primerak> listaPrimeraka = (ArrayList<Primerak>) so.getOdgovor();
        return listaPrimeraka;

    }

    public int vratiBrojSlobodnihPrimeraka(Knjiga knjiga) {

        brojSlobodnihPrimeraka = 0;
        listaPrimeraka = vratiPrimerkeZaSelektovanuKnjigu(selektovanaKnjiga);
        for (Primerak primerak : listaPrimeraka) {
            if (!primerak.isZaduzen() && !primerak.isRashodovan()) {
                brojSlobodnihPrimeraka++;
            }
        }
        return brojSlobodnihPrimeraka;
    }

    public int vratiIndeksSelektovaneKnjige() {

        return tblKnjige.getSelectedRow();

    }

    public Knjiga vratiSelektovanuKnjigu(int indeks) {

        ModelTabeleKnjiga modelTabeleKnjiga = (ModelTabeleKnjiga) tblKnjige.getModel();
        Knjiga knjiga = null;
        try {
            knjiga = modelTabeleKnjiga.vratiKnjigu(indeks);
        } catch (IOException ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
        return knjiga;

    }

    private Object[][] popuniRedove(ArrayList<Knjiga> listaKnjiga) {

        Object[][] rows = new Object[listaKnjiga.size()][10];
        for (int i = 0; i < listaKnjiga.size(); i++) {
            rows[i][0] = listaKnjiga.get(i).getIsbn();
            rows[i][1] = listaKnjiga.get(i).getNaziv();
            rows[i][2] = listaKnjiga.get(i).getPisac();
            rows[i][3] = listaKnjiga.get(i).getGodinaIzdanja();
            rows[i][4] = listaKnjiga.get(i).getPismo();
            rows[i][5] = listaKnjiga.get(i).getBrojStrana();
            rows[i][6] = listaKnjiga.get(i).getZanr();
            rows[i][7] = listaKnjiga.get(i).getPovez();

            if (listaKnjiga.get(i).getSlika() != null) {
                ImageIcon image = new ImageIcon(new ImageIcon(listaKnjiga.get(i).getSlika()).getImage().getScaledInstance(100, 150, Image.SCALE_SMOOTH));

                rows[i][8] = image;
            } else {
                rows[i][8] = null;
            }
            rows[i][9] = listaKnjiga.get(i).getListaPrimeraka();

        }
        return rows;

    }

    public void popuniComboboxPrimeraka() {
        ArrayList<Primerak> listaPrimeraka = vratiPrimerkeZaSelektovanuKnjigu(selektovanaKnjiga);
        ArrayList<Primerak> listaRaspolozivihPrimeraka = new ArrayList<>();
        for (Primerak primerak : listaPrimeraka) {
            if (!primerak.isZaduzen() && !primerak.isRashodovan()) {
                listaRaspolozivihPrimeraka.add(primerak);
            }
        }
        cmbPrimerci.removeAllItems();
        for (Primerak primerak : listaRaspolozivihPrimeraka) {
            cmbPrimerci.addItem(primerak);
        }
        if (listaRaspolozivihPrimeraka.isEmpty()) {
            cmbPrimerci.setVisible(false);
        }
    }

    public Clan getSelektovaniClan() {
        return selektovaniClan;
    }

    public void setSelektovaniClan(Clan selektovaniClan) {
        this.selektovaniClan = selektovaniClan;
    }

    public Zaduzenje getZaduzenje() {
        return zaduzenje;
    }

    public void setZaduzenje(Zaduzenje zaduzenje) {
        this.zaduzenje = zaduzenje;
    }

    public Knjiga getSelektovanaKnjiga() {
        return selektovanaKnjiga;
    }

    public void setSelektovanaKnjiga(Knjiga selektovanaKnjiga) {
        this.selektovanaKnjiga = selektovanaKnjiga;
    }

    public Radnik getUlogovaniRadnik() {
        return ulogovaniRadnik;
    }

    public void setUlogovaniRadnik(Radnik ulogovaniRadnik) {
        this.ulogovaniRadnik = ulogovaniRadnik;
    }

    public Primerak getSelektovaniPrimerak() {
        return selektovaniPrimerak;
    }

    public void setSelektovaniPrimerak(Primerak selektovaniPrimerak) {
        this.selektovaniPrimerak = selektovaniPrimerak;
    }

    public javax.swing.JButton getBtnZaduzi() {
        return btnZaduzi;
    }

    public void setBtnZaduzi(javax.swing.JButton btnZaduzi) {
        this.btnZaduzi = btnZaduzi;
    }
    
    
}
