/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import forme.potvrde.PotvrdaONovojKnjizi;
import domen.Knjiga;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import static modeli.ModelTabeleKnjiga.getBufferedImage;
import niti.NitOsluskujNovaKnjiga;

/**
 *
 * @author STEFAN94
 */
public class UnesiNovuKnjiguForma extends javax.swing.JDialog {

    Knjiga selektovanaKnjiga;
    byte[] slika = null;

    /**
     * Creates new form IzmeniPodatkeOKnjiziForma
     *
     * @param parent
     * @param modal
     */
    public UnesiNovuKnjiguForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.getContentPane().setBackground(java.awt.Color.lightGray);
        initComponents();
        popuniCombobox();
        NitOsluskujNovaKnjiga nonk = new NitOsluskujNovaKnjiga(this);
        nonk.start();
        
        Dimension screenSize, frameSize;
        int x, y;
        screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        frameSize = getSize();
        x = (screenSize.width - frameSize.width) / 2;
        y = (screenSize.height - frameSize.height) / 2;
        setLocation(x, y);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIsbn = new javax.swing.JTextField();
        txtNaziv = new javax.swing.JTextField();
        txtPisac = new javax.swing.JTextField();
        txtGodinaIzdanja = new javax.swing.JTextField();
        txtPismo = new javax.swing.JTextField();
        txtBrojStrana = new javax.swing.JTextField();
        cmbZanr = new javax.swing.JComboBox<>();
        txtPovez = new javax.swing.JTextField();
        btnUnesi = new javax.swing.JButton();
        btnSlika = new javax.swing.JButton();
        btnOdustani = new javax.swing.JButton();
        spnBrojPrimeraka = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unos nove knjige");

        jLabel1.setText("ISBN:");

        jLabel2.setText("Naziv:");

        jLabel3.setText("Pisac:");

        jLabel4.setText("Godina izdanja:");

        jLabel5.setText("Pismo:");

        jLabel6.setText("Broj strana:");

        jLabel7.setText("Zanr:");

        jLabel8.setText("Povez:");

        jLabel9.setText("Broj primeraka:");

        jLabel10.setText("Slika:");

        txtPismo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPismoActionPerformed(evt);
            }
        });

        cmbZanr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnUnesi.setText("Unesi");
        btnUnesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiActionPerformed(evt);
            }
        });

        btnSlika.setText("Izaberite sliku");
        btnSlika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlikaActionPerformed(evt);
            }
        });

        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(txtIsbn))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(txtNaziv))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(txtPisac))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(txtGodinaIzdanja))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(txtPismo))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(txtBrojStrana))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(cmbZanr, 0, 371, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtPovez))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addComponent(spnBrojPrimeraka, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(18, 18, 18)
                            .addComponent(btnSlika)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUnesi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 281, Short.MAX_VALUE)
                        .addComponent(btnOdustani)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPisac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGodinaIzdanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPismo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBrojStrana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbZanr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPovez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(spnBrojPrimeraka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(btnSlika))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUnesi)
                    .addComponent(btnOdustani))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPismoActionPerformed

    }//GEN-LAST:event_txtPismoActionPerformed

    private void btnUnesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiActionPerformed
       
        if (txtBrojStrana.getText().isEmpty() || txtGodinaIzdanja.getText().isEmpty()
                || txtIsbn.getText().isEmpty() || txtNaziv.getText().isEmpty() || txtPisac.getText().isEmpty() || txtPovez.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Molimo Vas da popunite sva polja");
            return;
        }

        int brojPrimeraka;
        brojPrimeraka = (int) spnBrojPrimeraka.getValue();
        if (brojPrimeraka < 0) {
            JOptionPane.showMessageDialog(this, "Broj primeraka mora biti pozitivan broj");
            return;
        }

        int brojStrana;
        try {
            brojStrana = Integer.parseInt(txtBrojStrana.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Molimo Vas da u polje 'broj strana' unosite samo brojeve");
            return;
        }
        if (brojStrana < 0) {
            JOptionPane.showMessageDialog(this, "Broj strana mora biti pozitivan broj");
            return;
        }
        
        String godinaIzdanja = txtGodinaIzdanja.getText();
        String godinaIzdanjaPattern = "^[1|2][0-9]{3}$";
        if (!godinaIzdanja.matches(godinaIzdanjaPattern)) {
            JOptionPane.showMessageDialog(this, "Molimo Vas da u polje 'godina izdanja' unesete validnu godinu");
            return;
        }

        String isbn = txtIsbn.getText();
        String naziv = txtNaziv.getText();
        String pisac = txtPisac.getText();
        String povez = txtPovez.getText();
        String pismo = txtPismo.getText();
        String zanr = (String) cmbZanr.getSelectedItem();

        GlavnaForma gf = (GlavnaForma) this.getParent();
        ArrayList<Knjiga> listaKnjiga = gf.getListaKnjiga();
        for (Knjiga knjiga : listaKnjiga) {
            if(isbn.equals(knjiga.getIsbn())){
                JOptionPane.showMessageDialog(this, "Knjiga sa datim ISBN-om vec postoji");
                return;
            }
        }
        
        Knjiga novaKnjiga = new Knjiga(isbn, naziv, pisac, godinaIzdanja, pismo, brojStrana, zanr, povez, slika, null);
        novaKnjiga.setBrojPrimeraka(brojPrimeraka);
        GlavnaForma glavnaForma = (GlavnaForma) this.getParent();
        glavnaForma.setNovaKnjiga(novaKnjiga);

        PotvrdaONovojKnjizi potvrdaONovojKnjizi = new PotvrdaONovojKnjizi(glavnaForma, true);
        potvrdaONovojKnjizi.pack();
        potvrdaONovojKnjizi.setVisible(true);

    }//GEN-LAST:event_btnUnesiActionPerformed

    private void btnSlikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlikaActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        FileFilter filter = new FileNameExtensionFilter("JPEG file", "jpg", "jpeg");
        fileChooser.setFileFilter(filter);
        fileChooser.showOpenDialog(null);
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        File fajl = fileChooser.getSelectedFile();

        String fileName = fajl.getName();
        btnSlika.setText(fileName);
        try {
            slika = Files.readAllBytes(fajl.toPath());
            ImageIcon sl = new ImageIcon(slika);
            Image image = sl.getImage();
            Image newimg = image.getScaledInstance(100, 150, java.awt.Image.SCALE_SMOOTH);
            sl = new ImageIcon(newimg);
            BufferedImage bi = getBufferedImage(sl.getImage());
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            ImageIO.write(bi, "jpg", baos);
            slika = baos.toByteArray();
        } catch (IOException ex) {
            slika = selektovanaKnjiga.getSlika();
        }

        if (slika == null) {
            slika = selektovanaKnjiga.getSlika();
        }

    }//GEN-LAST:event_btnSlikaActionPerformed

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed

        dispose();
        
    }//GEN-LAST:event_btnOdustaniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnesiNovuKnjiguForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnesiNovuKnjiguForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnesiNovuKnjiguForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnesiNovuKnjiguForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UnesiNovuKnjiguForma dialog = new UnesiNovuKnjiguForma(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdustani;
    private javax.swing.JButton btnSlika;
    private javax.swing.JButton btnUnesi;
    private javax.swing.JComboBox<String> cmbZanr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner spnBrojPrimeraka;
    private javax.swing.JTextField txtBrojStrana;
    private javax.swing.JTextField txtGodinaIzdanja;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtPisac;
    private javax.swing.JTextField txtPismo;
    private javax.swing.JTextField txtPovez;
    // End of variables declaration//GEN-END:variables

    private void popuniCombobox() {
        
        cmbZanr.removeAllItems();
        String[] zanrovi = Knjiga.LISTA_ZANROVA;

        for (int i = 0; i < zanrovi.length - 1; i++) {
            cmbZanr.addItem(zanrovi[i]);
        }
    }

    public javax.swing.JButton getBtnUnesi() {
        return btnUnesi;
    }

    public void setBtnUnesi(javax.swing.JButton btnUnesi) {
        this.btnUnesi = btnUnesi;
    }

    public javax.swing.JTextField getTxtBrojStrana() {
        return txtBrojStrana;
    }

    public void setTxtBrojStrana(javax.swing.JTextField txtBrojStrana) {
        this.txtBrojStrana = txtBrojStrana;
    }

    public javax.swing.JTextField getTxtGodinaIzdanja() {
        return txtGodinaIzdanja;
    }

    public void setTxtGodinaIzdanja(javax.swing.JTextField txtGodinaIzdanja) {
        this.txtGodinaIzdanja = txtGodinaIzdanja;
    }

    public javax.swing.JTextField getTxtIsbn() {
        return txtIsbn;
    }

    public void setTxtIsbn(javax.swing.JTextField txtIsbn) {
        this.txtIsbn = txtIsbn;
    }

    public javax.swing.JTextField getTxtNaziv() {
        return txtNaziv;
    }

    public void setTxtNaziv(javax.swing.JTextField txtNaziv) {
        this.txtNaziv = txtNaziv;
    }

    public javax.swing.JTextField getTxtPisac() {
        return txtPisac;
    }

    public void setTxtPisac(javax.swing.JTextField txtPisac) {
        this.txtPisac = txtPisac;
    }

    public javax.swing.JTextField getTxtPismo() {
        return txtPismo;
    }

    public void setTxtPismo(javax.swing.JTextField txtPismo) {
        this.txtPismo = txtPismo;
    }

    public javax.swing.JTextField getTxtPovez() {
        return txtPovez;
    }

    public void setTxtPovez(javax.swing.JTextField txtPovez) {
        this.txtPovez = txtPovez;
    }

    public javax.swing.JSpinner getSpnBrojPrimeraka() {
        return spnBrojPrimeraka;
    }

    public void setSpnBrojPrimeraka(javax.swing.JSpinner spnBrojPrimeraka) {
        this.spnBrojPrimeraka = spnBrojPrimeraka;
    }
}
