/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Clan;
import domen.Knjiga;
import domen.Primerak;
import domen.Radnik;
import domen.Zaduzenje;
import forme.potvrde.PotvrdaORazduzivanju;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.LayoutManager;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import komunikacija.Komunikacija;
import modeli.ModelTabeleZaduzenja;
import operacije.Operacija;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author STEFAN94
 */
public class ZaduzenjaForma extends javax.swing.JFrame {

    private ArrayList<Zaduzenje> listaZaduzenja = new ArrayList<>();
    private ArrayList<Primerak> listaPrimeraka = new ArrayList<>();
    private Radnik ulogovaniRadnik;
    private GlavnaForma gf;
    private Knjiga selektovanaKnjiga;
    private Zaduzenje selektovanoZaduzenje;
    private int brojSlobodnihPrimeraka;
    private Clan selektovanClanZaZaduzenje;
    private String brPrimeraka;
    private String info;
    private Primerak selektovaniPrimerak;

    /**
     * Creates new form ZaduzenjaForma
     *
     * @param gf
     */
    public ZaduzenjaForma(GlavnaForma gf) {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.gf = gf;
        initComponents();
        this.getContentPane().setBackground(java.awt.Color.lightGray);
        popuniTabelu();
        ulogovaniRadnik = gf.getUlogovaniRadnik();
        gf.getBtnZaduziKnjigu().setEnabled(false);
        int indeks = gf.vratiIndeksSelektovaneKnjige();
        selektovanaKnjiga = gf.vratiSelektovanuKnjigu(indeks);
        vratiBrojSlobodnihPrimeraka(selektovanaKnjiga);
        brPrimeraka = lblBrSlobodnihPrimeraka.getText();
        lblBrSlobodnihPrimeraka.setText(brPrimeraka);
        lblBrPrimeraka.setText("" + brojSlobodnihPrimeraka);
        info = lblZaduzenaKnjigaLbl.getText();
        lblZaduzenaKnjigaLbl.setText(info + " " + selektovanaKnjiga.getNaziv());
        btnRazduzi.setEnabled(false);
        this.setTitle("Zaduzenja za knjigu: " + selektovanaKnjiga.getNaziv());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPretragaZaduzenja = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblZaduzenja = new javax.swing.JTable();
        btnZaduzi = new javax.swing.JButton();
        btnRazduzi = new javax.swing.JButton();
        lblZaduzenaKnjigaLbl = new javax.swing.JLabel();
        lblBrSlobodnihPrimeraka = new javax.swing.JLabel();
        lblBrPrimeraka = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Pretraga zaduzenja(Ime/Prezime/JMBG/Datum zaduzenja):");

        txtPretragaZaduzenja.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPretragaZaduzenjaKeyReleased(evt);
            }
        });

        tblZaduzenja.setBackground(new java.awt.Color(0, 102, 102));
        tblZaduzenja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblZaduzenja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblZaduzenjaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblZaduzenja);

        btnZaduzi.setText("Novo zaduzenje");
        btnZaduzi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaduziActionPerformed(evt);
            }
        });

        btnRazduzi.setText("Razduzi");
        btnRazduzi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRazduziActionPerformed(evt);
            }
        });

        lblZaduzenaKnjigaLbl.setText("Zaduzenja za knjigu:");

        lblBrSlobodnihPrimeraka.setText("Broj slobodnih primeraka:");

        lblBrPrimeraka.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnZaduzi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRazduzi))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPretragaZaduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblZaduzenaKnjigaLbl)
                                .addGap(77, 77, 77)
                                .addComponent(lblBrSlobodnihPrimeraka)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblBrPrimeraka)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPretragaZaduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZaduzenaKnjigaLbl)
                    .addComponent(lblBrSlobodnihPrimeraka)
                    .addComponent(lblBrPrimeraka))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRazduzi)
                    .addComponent(btnZaduzi)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        gf.getBtnZaduziKnjigu().setEnabled(true);

    }//GEN-LAST:event_formWindowClosed

    private void txtPretragaZaduzenjaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretragaZaduzenjaKeyReleased

        String pretraga = txtPretragaZaduzenja.getText();
        String patternZaPretragu = "^" + pretraga.toLowerCase() + ".*";
        ArrayList<Zaduzenje> listaPretrazenihZaduzenja = new ArrayList<>();
        for (Zaduzenje zaduzenje : listaZaduzenja) {
            String jmbgString = zaduzenje.getClan().getJmbg() + "";

            String datumZadStr = zaduzenje.getDatumZaduzenja().toString();
            String datumRazStr = "";
            if (zaduzenje.getDatumRazduzenja() != null) {
                datumRazStr = zaduzenje.getDatumRazduzenja().toString();
            } else {
                datumRazStr = "0000-00-00";
            }

            if (zaduzenje.getClan().getIme().toLowerCase().matches(patternZaPretragu)
                    || zaduzenje.getClan().getPrezime().toLowerCase().matches(patternZaPretragu)
                    || zaduzenje.getClan().getIme().concat(" ").concat(zaduzenje.getClan().getPrezime()).toLowerCase().matches(patternZaPretragu)
                    || zaduzenje.getClan().getPrezime().concat(" ").concat(zaduzenje.getClan().getIme()).toLowerCase().matches(patternZaPretragu)
                    || jmbgString.matches(patternZaPretragu)
                    || datumZadStr.matches(patternZaPretragu)
                    || datumRazStr.matches(patternZaPretragu)) {
                listaPretrazenihZaduzenja.add(zaduzenje);
            }
        }
        ModelTabeleZaduzenja mtz = (ModelTabeleZaduzenja) tblZaduzenja.getModel();
        mtz.azurirajTabelu(listaPretrazenihZaduzenja);

        btnRazduzi.setEnabled(false);

    }//GEN-LAST:event_txtPretragaZaduzenjaKeyReleased

    private void btnRazduziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRazduziActionPerformed

        int indeks = tblZaduzenja.getSelectedRow();
        ModelTabeleZaduzenja mtz = (ModelTabeleZaduzenja) tblZaduzenja.getModel();
        selektovanoZaduzenje = mtz.vratiSelektovanoZaduzenje(indeks);
        if (selektovanoZaduzenje.getDatumRazduzenja() != null) {
            JOptionPane.showMessageDialog(this, "Clan je vec razduzio datu knjigu");
            return;
        }
        selektovanoZaduzenje.getPrimerak().setRashodovan(false);
        selektovanoZaduzenje.getPrimerak().setZaduzen(false);
        PotvrdaORazduzivanju por = new PotvrdaORazduzivanju(this, true);
        por.pack();
        por.setVisible(true);
        btnRazduzi.setEnabled(false);

    }//GEN-LAST:event_btnRazduziActionPerformed

    private void tblZaduzenjaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblZaduzenjaMouseClicked

        btnRazduzi.setEnabled(true);

    }//GEN-LAST:event_tblZaduzenjaMouseClicked

    private void btnZaduziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaduziActionPerformed

        ClanoviZaZaduzenje czz = new ClanoviZaZaduzenje(this, true);
        int visina = (int) Toolkit.getDefaultToolkit().getScreenSize().getHeight() - 30;
        int sirina = (int) Toolkit.getDefaultToolkit().getScreenSize().getWidth() + 20;
        czz.setPreferredSize(new Dimension(sirina, visina));
        czz.setBounds(-10, 0, sirina, visina);
        czz.pack();
        czz.setVisible(true);

    }//GEN-LAST:event_btnZaduziActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ZaduzenjaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ZaduzenjaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ZaduzenjaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ZaduzenjaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ZaduzenjaForma().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRazduzi;
    private javax.swing.JButton btnZaduzi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBrPrimeraka;
    private javax.swing.JLabel lblBrSlobodnihPrimeraka;
    private javax.swing.JLabel lblZaduzenaKnjigaLbl;
    private javax.swing.JTable tblZaduzenja;
    private javax.swing.JTextField txtPretragaZaduzenja;
    // End of variables declaration//GEN-END:variables

    public void popuniTabelu() {

        int indeksSelektovaneKnjige = gf.vratiIndeksSelektovaneKnjige();
        selektovanaKnjiga = gf.vratiSelektovanuKnjigu(indeksSelektovaneKnjige);
//        Primerak p = new Primerak();
//        p.setIsbn(selektovanaKnjiga.getIsbn());
        listaZaduzenja = this.vratiZaduzenja();
//        ArrayList<Zaduzenje> listaZaduzenjaZaSelektovanuKnjigu = new ArrayList<>();
//        for (Zaduzenje zaduzenje : listaZaduzenja) {
//            if (zaduzenje.getKnjiga().getIsbn().equals(selektovanaKnjiga.getIsbn())) {
//                listaZaduzenjaZaSelektovanuKnjigu.add(zaduzenje);
//            }
//        }
        ModelTabeleZaduzenja mtz = new ModelTabeleZaduzenja(listaZaduzenja);
        tblZaduzenja.setModel(mtz);

    }

    private ArrayList<Zaduzenje> vratiZaduzenja() {
        KlijentskiZahtev kz = new KlijentskiZahtev();
        Zaduzenje z = new Zaduzenje();
        z.setKnjiga(selektovanaKnjiga);
        kz.setParametar(z);
        kz.setOperacija(Operacija.VRATI_ZADUZENJA);

        komunikacija.Komunikacija.getInstanca().posaljiKlijentskiZahtev(kz);
        ServerskiOdgovor so = komunikacija.Komunikacija.getInstanca().primiServerskiOdgovor();

        ArrayList<Zaduzenje> listaZaduzenja = (ArrayList<Zaduzenje>) so.getOdgovor();

        return listaZaduzenja;
    }

    private ArrayList<Primerak> vratiPrimerkeZaSelektovanuKnjigu(Primerak primerak) {

        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacija.VRATI_PRIMERKE);
        kz.setParametar(primerak);

        Komunikacija.getInstanca().posaljiKlijentskiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstanca().primiServerskiOdgovor();
        ArrayList<Primerak> listaPrimeraka = (ArrayList<Primerak>) so.getOdgovor();
        return listaPrimeraka;

    }

    public int vratiBrojSlobodnihPrimeraka(Knjiga knjiga) {

        brojSlobodnihPrimeraka = 0;
        Primerak p = new Primerak();
        p.setIsbn(selektovanaKnjiga.getIsbn());
        listaPrimeraka = vratiPrimerkeZaSelektovanuKnjigu(p);
        for (Primerak primerak : listaPrimeraka) {
            if (!primerak.isZaduzen() && !primerak.isRashodovan()) {
                brojSlobodnihPrimeraka++;
            }
        }
        return brojSlobodnihPrimeraka;

    }

    public void azurirajBrPrimeraka() {
        lblBrPrimeraka.setText(brojSlobodnihPrimeraka + "");

    }

    public Zaduzenje getSelektovanoZaduzenje() {
        return selektovanoZaduzenje;
    }

    public void setSelektovanoZaduzenje(Zaduzenje selektovanoZaduzenje) {
        this.selektovanoZaduzenje = selektovanoZaduzenje;
    }

    public Clan getSelektovanClanZaZaduzenje() {
        return selektovanClanZaZaduzenje;
    }

    public void setSelektovanClanZaZaduzenje(Clan selektovanClanZaZaduzenje) {
        this.selektovanClanZaZaduzenje = selektovanClanZaZaduzenje;
    }

    public Knjiga getSelektovanaKnjiga() {
        return selektovanaKnjiga;
    }

    public void setSelektovanaKnjiga(Knjiga selektovanaKnjiga) {
        this.selektovanaKnjiga = selektovanaKnjiga;
    }

    public ArrayList<Zaduzenje> getListaZaduzenja() {
        return listaZaduzenja;
    }

    public void setListaZaduzenja(ArrayList<Zaduzenje> listaZaduzenja) {
        this.listaZaduzenja = listaZaduzenja;
    }

    public ArrayList<Primerak> getListaPrimeraka() {
        return listaPrimeraka;
    }

    public void setListaPrimeraka(ArrayList<Primerak> listaPrimeraka) {
        this.listaPrimeraka = listaPrimeraka;
    }

    public Radnik getUlogovaniRadnik() {
        return ulogovaniRadnik;
    }

    public void setUlogovaniRadnik(Radnik ulogovaniRadnik) {
        this.ulogovaniRadnik = ulogovaniRadnik;
    }

    public javax.swing.JLabel getLblBrSlobodnihPrimeraka() {
        return lblBrSlobodnihPrimeraka;
    }

    public void setLblBrSlobodnihPrimeraka(javax.swing.JLabel lblBrSlobodnihPrimeraka) {
        this.lblBrSlobodnihPrimeraka = lblBrSlobodnihPrimeraka;
    }

    public int getBrojSlobodnihPrimeraka() {
        return brojSlobodnihPrimeraka;
    }

    public void setBrojSlobodnihPrimeraka(int brojSlobodnihPrimeraka) {
        this.brojSlobodnihPrimeraka = brojSlobodnihPrimeraka;
    }

    public Primerak getSelektovaniPrimerak() {
        return selektovaniPrimerak;
    }

    public void setSelektovaniPrimerak(Primerak selektovaniPrimerak) {
        this.selektovaniPrimerak = selektovaniPrimerak;
    }

}
