/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Clan;
import domen.Knjiga;
import domen.Primerak;
import domen.Radnik;
import domen.Zaduzenje;

import forme.potvrde.PotvrdaORazduzivanjuClana;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;

import modeli.ModelTabeleZaduzenjaClana;
import operacije.Operacija;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author STEFAN94
 */
public class ZaduzenjaClanovaForma extends javax.swing.JFrame {

    private Clan clanZaduzenja;
    private Zaduzenje selektovanoZaduzenje;
    private ClanoviForma cf;
    private Radnik ulogovaniRadnik;
    private Knjiga selektovanaKnjiga;
    private ArrayList<Primerak> listaPrimeraka = new ArrayList<>();
    private ArrayList<Zaduzenje> listaZaduzenja;
    private Primerak selektovaniPrimerak = new Primerak();

    
    /**
     * Creates new form ZaduzenjaClanovaForma
     *
     * @param clanZaduzenja
     * @param ulogovaniRadnik
     */
    public ZaduzenjaClanovaForma(Clan clanZaduzenja, Radnik ulogovaniRadnik) {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        cf = (ClanoviForma) this.getParent();
        this.clanZaduzenja = clanZaduzenja;
        this.ulogovaniRadnik = ulogovaniRadnik;
        this.getContentPane().setBackground(java.awt.Color.lightGray);
        initComponents();
        this.setTitle("Zaduzenja clana: " + clanZaduzenja.getIme() + " " + clanZaduzenja.getPrezime());
        popuniTabelu();
        btnRazduzi.setEnabled(false);
        System.out.println("" + ulogovaniRadnik.getRadnikID());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblZaduzenjaClana = new javax.swing.JTable();
        btnRazduzi = new javax.swing.JButton();
        btnNovoZaduzenje = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Pretraga zaduzenja clana(Naziv/Pisac/ISBN):");

        txtPretraga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPretragaKeyReleased(evt);
            }
        });

        tblZaduzenjaClana.setBackground(new java.awt.Color(0, 102, 102));
        tblZaduzenjaClana.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblZaduzenjaClana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblZaduzenjaClanaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblZaduzenjaClana);

        btnRazduzi.setText("Razduzi");
        btnRazduzi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRazduziActionPerformed(evt);
            }
        });

        btnNovoZaduzenje.setText("Novo zaduzenje");
        btnNovoZaduzenje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoZaduzenjeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnNovoZaduzenje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRazduzi))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(0, 133, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRazduzi)
                    .addComponent(btnNovoZaduzenje)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblZaduzenjaClanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblZaduzenjaClanaMouseClicked

        btnRazduzi.setEnabled(true);
        
    }//GEN-LAST:event_tblZaduzenjaClanaMouseClicked

    private void btnRazduziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRazduziActionPerformed

        int indeksSelektovanogZaduzenja = tblZaduzenjaClana.getSelectedRow();
        ModelTabeleZaduzenjaClana mtzc = (ModelTabeleZaduzenjaClana) tblZaduzenjaClana.getModel();
        
        selektovanoZaduzenje = mtzc.vratiSelektovanoZaduzenje(indeksSelektovanogZaduzenja);
        if (selektovanoZaduzenje.getDatumRazduzenja() != null) {
            JOptionPane.showMessageDialog(this, "Clan je vec razduzio datu knjigu");
            return;
        }

        PotvrdaORazduzivanjuClana porc = new PotvrdaORazduzivanjuClana(this, true);
        porc.pack();
        porc.setVisible(true);

    }//GEN-LAST:event_btnRazduziActionPerformed

    private void btnNovoZaduzenjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoZaduzenjeActionPerformed
        
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacija.PROVERI_CLANARINU);
        kz.setParametar(clanZaduzenja);

        Komunikacija.getInstanca().posaljiKlijentskiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstanca().primiServerskiOdgovor();

        boolean clanarinaAktivna = (boolean) so.getOdgovor();
        if (clanarinaAktivna) {
            KnjigeZaZaduzenje kzz = new KnjigeZaZaduzenje(this, true);
            int visina = (int) Toolkit.getDefaultToolkit().getScreenSize().getHeight() - 30;
            int sirina = (int) Toolkit.getDefaultToolkit().getScreenSize().getWidth() + 20;
            kzz.setPreferredSize(new Dimension(sirina, visina));
            kzz.setBounds(-10, 0, sirina, visina);
            kzz.pack();
            kzz.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Clanu je istekla clanarina");
        }

    }//GEN-LAST:event_btnNovoZaduzenjeActionPerformed

    private void txtPretragaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretragaKeyReleased

        String pretraga = txtPretraga.getText();

        String patternZaPretragu = "^" + pretraga.toLowerCase() + ".*";
        ArrayList<Zaduzenje> listaPretrazenihZaduzenja = new ArrayList<>();
        for (Zaduzenje zaduzenje : listaZaduzenja) {

            String datumZadStr = zaduzenje.getDatumZaduzenja().toString();
            String datumRazStr = "";
            if (zaduzenje.getDatumRazduzenja() != null) {
                datumRazStr = zaduzenje.getDatumRazduzenja().toString();
            } else {
                datumRazStr = "0000-00-00";
            }

            if (zaduzenje.getKnjiga().getNaziv().toLowerCase().matches(patternZaPretragu)
                    || zaduzenje.getKnjiga().getPisac().toLowerCase().matches(patternZaPretragu)
                    || zaduzenje.getKnjiga().getIsbn().toLowerCase().matches(patternZaPretragu)
                    || datumZadStr.matches(patternZaPretragu)
                    || datumRazStr.matches(patternZaPretragu)) {
                listaPretrazenihZaduzenja.add(zaduzenje);
            }
        }
        ModelTabeleZaduzenjaClana mtz = (ModelTabeleZaduzenjaClana) tblZaduzenjaClana.getModel();
        mtz.azurirajTabelu(listaPretrazenihZaduzenja);

        btnRazduzi.setEnabled(false);
    }//GEN-LAST:event_txtPretragaKeyReleased

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ZaduzenjaClanovaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ZaduzenjaClanovaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ZaduzenjaClanovaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ZaduzenjaClanovaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ZaduzenjaClanovaForma().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovoZaduzenje;
    private javax.swing.JButton btnRazduzi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblZaduzenjaClana;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables

    public void popuniTabelu() {
        
        KlijentskiZahtev kz = new KlijentskiZahtev();
        Zaduzenje z = new Zaduzenje();
        z.setClan(clanZaduzenja);
        kz.setParametar(z);
        kz.setOperacija(operacije.Operacija.VRATI_ZADUZENJA);

        komunikacija.Komunikacija.getInstanca().posaljiKlijentskiZahtev(kz);
        ServerskiOdgovor so = komunikacija.Komunikacija.getInstanca().primiServerskiOdgovor();

        listaZaduzenja = (ArrayList<Zaduzenje>) so.getOdgovor();
//        ArrayList<Zaduzenje> listaZaduzenjaSelektovanogClana = new ArrayList<>();
//        for (Zaduzenje zaduzenje : listaZaduzenja) {
//            if(zaduzenje.getClan().getClanID() == clanZaduzenja.getClanID()){
//                listaZaduzenjaSelektovanogClana.add(zaduzenje);
//            }
//        }
        ModelTabeleZaduzenjaClana mtzc = new ModelTabeleZaduzenjaClana(listaZaduzenja);
        tblZaduzenjaClana.setModel(mtzc);

    }

    public Clan getClanZaduzenja() {
        return clanZaduzenja;
    }

    public void setClanZaduzenja(Clan clanZaduzenja) {
        this.clanZaduzenja = clanZaduzenja;
    }

    public Zaduzenje getSelektovanoZaduzenje() {
        return selektovanoZaduzenje;
    }

    public void setSelektovanoZaduzenje(Zaduzenje selektovanoZaduzenje) {
        this.selektovanoZaduzenje = selektovanoZaduzenje;
    }

    public Radnik getUlogovaniRadnik() {
        return ulogovaniRadnik;
    }

    public void setUlogovaniRadnik(Radnik ulogovaniRadnik) {
        this.ulogovaniRadnik = ulogovaniRadnik;
    }

    public Knjiga getSelektovanaKnjiga() {
        return selektovanaKnjiga;
    }

    public void setSelektovanaKnjiga(Knjiga selektovanaKnjiga) {
        this.selektovanaKnjiga = selektovanaKnjiga;
    }

    public ArrayList<Primerak> getListaPrimeraka() {
        return listaPrimeraka;
    }

    public void setListaPrimeraka(ArrayList<Primerak> listaPrimeraka) {
        this.listaPrimeraka = listaPrimeraka;
    }

    public javax.swing.JButton getBtnRazduzi() {
        return btnRazduzi;
    }

    public void setBtnRazduzi(javax.swing.JButton btnRazduzi) {
        this.btnRazduzi = btnRazduzi;
    }

    public Primerak getSelektovaniPrimerak() {
        return selektovaniPrimerak;
    }

    public void setSelektovaniPrimerak(Primerak selektovaniPrimerak) {
        this.selektovaniPrimerak = selektovaniPrimerak;
    }
}
