/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.potvrde;

import domen.Clan;
import domen.Knjiga;
import domen.Primerak;
import domen.Radnik;
import domen.Zaduzenje;
import forme.ClanoviZaZaduzenje;

import forme.ZaduzenjaForma;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import operacije.Operacija;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author STEFAN94
 */
public class PotvrdaOZaduzenju extends javax.swing.JDialog {

    private Clan selektovaniClan;
    private Knjiga selektovanaKnjiga;
    private ZaduzenjaForma zf;
    private ArrayList<Primerak> listaPrimeraka;
    private Radnik radnikZaduzio;
    private ClanoviZaZaduzenje czz;
    
    
    /**
     * Creates new form PotvrdaOZaduzenju
     *
     * @param parent
     * @param modal
     */
    public PotvrdaOZaduzenju(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        zf = (ZaduzenjaForma) this.getParent();
        initComponents();
        this.getContentPane().setBackground(java.awt.Color.lightGray);
        radnikZaduzio = zf.getUlogovaniRadnik();
        selektovanaKnjiga = zf.getSelektovanaKnjiga();
        selektovaniClan = zf.getSelektovanClanZaZaduzenje();
        listaPrimeraka = zf.getListaPrimeraka();
        lblInfo.setText("Da li ste sigurni da zelite da zaduzite datu knjigu " + selektovanaKnjiga.getNaziv() + " Clanu: " + selektovaniClan.getIme() + " " + selektovaniClan.getPrezime()+"?");
        
        Dimension screenSize, frameSize;
        int x, y;
        screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        frameSize = getSize();
        x = (screenSize.width - frameSize.width) / 2;
        y = (screenSize.height - frameSize.height) / 2;
        setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInfo = new javax.swing.JLabel();
        btnPotvrdi = new javax.swing.JButton();
        btnOdustani = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Zaduzi clana?");

        lblInfo.setText("jLabel1");

        btnPotvrdi.setText("Potvrdi");
        btnPotvrdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPotvrdiActionPerformed(evt);
            }
        });

        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInfo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPotvrdi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                        .addComponent(btnOdustani)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(lblInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPotvrdi)
                    .addComponent(btnOdustani))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed

        dispose();

    }//GEN-LAST:event_btnOdustaniActionPerformed

    private void btnPotvrdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPotvrdiActionPerformed

        Date danasnjiDatum = new Date();
        Primerak p = null;
//        for (Primerak primerak : listaPrimeraka) {
//            if (primerak.getIsbn().equals(selektovanaKnjiga.getIsbn()) && !primerak.isZaduzen() && !primerak.isRashodovan()) {
//                p = primerak;
//                p.setZaduzen(true);
//                break;
//            }
//        }
        p = zf.getSelektovaniPrimerak();
        p.setZaduzen(true);
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacija.VRATI_SLEDECI_ID);
        kz.setParametar(new Zaduzenje());
        
        komunikacija.Komunikacija.getInstanca().posaljiKlijentskiZahtev(kz);
        ServerskiOdgovor so = komunikacija.Komunikacija.getInstanca().primiServerskiOdgovor();
        int id = (int) so.getOdgovor();
        id++;
        Zaduzenje novoZaduzenje = new Zaduzenje(id, selektovaniClan, p, selektovanaKnjiga, danasnjiDatum, null, radnikZaduzio, null);
        kz = new KlijentskiZahtev();
        kz.setOperacija(Operacija.SACUVAJ_NOVO_ZADUZENJE);
        kz.setParametar(novoZaduzenje);

        komunikacija.Komunikacija.getInstanca().posaljiKlijentskiZahtev(kz);
        so = komunikacija.Komunikacija.getInstanca().primiServerskiOdgovor();

        JOptionPane.showMessageDialog(this, so.getPoruka());

        if ((boolean) so.getOdgovor()) {
            zf.vratiBrojSlobodnihPrimeraka(selektovanaKnjiga);
            zf.azurirajBrPrimeraka();
            zf.popuniTabelu();
            czz.popuniCmbPrimeraka();
        }
        this.dispose();
        
    }//GEN-LAST:event_btnPotvrdiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PotvrdaOZaduzenju.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PotvrdaOZaduzenju.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PotvrdaOZaduzenju.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PotvrdaOZaduzenju.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PotvrdaOZaduzenju dialog = new PotvrdaOZaduzenju(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdustani;
    private javax.swing.JButton btnPotvrdi;
    private javax.swing.JLabel lblInfo;
    // End of variables declaration//GEN-END:variables

    public ClanoviZaZaduzenje getCzz() {
        return czz;
    }

    public void setCzz(ClanoviZaZaduzenje czz) {
        this.czz = czz;
    }
}
