/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.login;

import domen.Radnik;
import forme.GlavnaForma;
import java.awt.Dimension;
import java.awt.Toolkit;

import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;

import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import operacije.Operacija;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author STEFAN94
 */
public class LogInForma extends javax.swing.JFrame {

    private ServerskiOdgovor serverskiOdgovor;
    private boolean izvrseno = false;

    /**
     * Creates new form LogInForma
     */
    public LogInForma() {

        this.getContentPane().setBackground(java.awt.Color.lightGray);
        initComponents();
        
        Dimension screenSize, frameSize;
        int x, y;
        screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        frameSize = getSize();
        x = (screenSize.width - frameSize.width) / 2;
        y = (screenSize.height - frameSize.height) / 2;
        setLocation(x, y);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtKorisnickoIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnUlogujSe = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();
        pasLozinka = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log In");

        jLabel1.setText("Korisnicko ime:");

        jLabel2.setText("Lozinka:");

        btnUlogujSe.setText("Uloguj se");
        btnUlogujSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUlogujSeActionPerformed(evt);
            }
        });

        btnOtkazi.setText("Otkazi");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtKorisnickoIme, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(pasLozinka))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUlogujSe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOtkazi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOtkazi))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUlogujSe)
                    .addComponent(pasLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUlogujSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUlogujSeActionPerformed

        if (txtKorisnickoIme.getText().isEmpty() || pasLozinka.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Molimo Vas da popunite sva polja u formi");
            return;
        }

        String korisnickoIme = txtKorisnickoIme.getText();
        char[] loz = pasLozinka.getPassword();
        String lozinka = new String(loz);

        Radnik radnikZaLogovanje = new Radnik();

        radnikZaLogovanje.setKorisnickoIme(korisnickoIme);
        radnikZaLogovanje.setLozinka(lozinka);

        KlijentskiZahtev klijentskiZahtev = new KlijentskiZahtev();
        klijentskiZahtev.setParametar(radnikZaLogovanje);
        klijentskiZahtev.setOperacija(Operacija.ULOGUJ_RADNIKA);
        Komunikacija.getInstanca().posaljiKlijentskiZahtev(klijentskiZahtev);
        serverskiOdgovor = Komunikacija.getInstanca().primiServerskiOdgovor();

        try {
            if (serverskiOdgovor != null && !(serverskiOdgovor.getOdgovor() instanceof Radnik) && (boolean) serverskiOdgovor.getOdgovor() == false) {
                JOptionPane.showMessageDialog(this, "Pogresni parametri");
                this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Pogresna lozinka");
        }
        Radnik ulogovaniRadnik;
        if (serverskiOdgovor.getOdgovor() instanceof Radnik) {
            ulogovaniRadnik = (Radnik) serverskiOdgovor.getOdgovor();
        } else {
            ulogovaniRadnik = null;
        }

        if (ulogovaniRadnik == null) {
            JOptionPane.showMessageDialog(this, "Neuspesno logovanje");
        } else {
            GlavnaForma glavnaForma = new GlavnaForma(ulogovaniRadnik);
            glavnaForma.pack();
            this.dispose();
            glavnaForma.setVisible(true);
        }

    }//GEN-LAST:event_btnUlogujSeActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed

        dispose();
        
    }//GEN-LAST:event_btnOtkaziActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInForma().setVisible(true);
            }
        });
    }

//    private static String encrypt(String strClearText, String strKey) throws Exception {
//        String strData = "";
//
//        try {
//            SecretKeySpec skeyspec = new SecretKeySpec(strKey.getBytes(), "Blowfish");
//            Cipher cipher = Cipher.getInstance("Blowfish");
//            cipher.init(Cipher.ENCRYPT_MODE, skeyspec);
//            byte[] encrypted = cipher.doFinal(strClearText.getBytes());
//            strData = new String(encrypted);
//
//        } catch (Exception e) {
//            e.printStackTrace();
//            throw new Exception(e);
//        }
//        return strData;
//    }

    public void ispisiPoruku(String s) {
        
        JOptionPane.showMessageDialog(this, s);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnUlogujSe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField pasLozinka;
    private javax.swing.JTextField txtKorisnickoIme;
    // End of variables declaration//GEN-END:variables

    public ServerskiOdgovor getSo() {
        return serverskiOdgovor;
    }

    public void setSo(ServerskiOdgovor so) {
        this.serverskiOdgovor = so;
    }

    public boolean isIzvrseno() {
        return izvrseno;
    }

    public void setIzvrseno(boolean izvrseno) {
        this.izvrseno = izvrseno;
    }
}
